### PR TITLE
Add JFR Flags

### PR DESCRIPTION
**Pull request by tajila**

### CODE REVIEW

**Comment by tajila** [comment]
The line ending check  failures are with the generated files

```
14:56:44  + git diff --check origin/openj9 HEAD
14:56:44  common/autoconf/generated-configure.sh:53502: new blank line at EOF.
14:56:44  jdk/make/closed/autoconf/generated-configure.sh:57314: new blank line at EOF.
```

**Comment by keithc-ca** [comment]
Please re-run `bash common/autoconf/autogen.sh` using GNU Autoconf 2.69 to avoid unnecessary changes to `generated-configure.sh` files.

**Comment by keithc-ca** [comment]
Please address the copyright notice issues:
```
15:26:01  The following files were modified and have incorrect copyrights
15:26:01  jdk/make/closed/autoconf/custom-hook.m4
15:26:01  	IBM Copyright date appears to be incorrect
15:26:01  jdk/make/closed/autoconf/custom-spec.gmk.in
15:26:01  	IBM Copyright date appears to be incorrect
```
and then re-run `bash common/autoconf/autogen.sh` (which contains the notice from `custom-hook.m4`).

**Review by keithc-ca — APPROVED** [review]

**Comment by keithc-ca** [comment]
Jenkins compile xlinux,zlinux jdk8

**Pull request merged**
