### PR TITLE
Add "-J-XstartOnFirstThread" for jdmpview on OSX

### PR DESCRIPTION
**Pull request by keithc-ca**
Hopefully, this will address the problem noted in eclipse/openj9#5127 on Java 8.

### CODE REVIEW

**Comment by keithc-ca** [comment]
Jenkins test extended osx jdk8

**Comment by keithc-ca** [comment]
Fix spelling of 'endif'.

**Comment by keithc-ca** [comment]
Jenkins test extended osx jdk8

**Comment by pshipton** [comment]
jenkins test sanity osx jdk8

**Comment by pshipton** [comment]
Seems to have fixed jdmpview, but the two testDDRExt_* tests must not be using jdmpview and will need to be fixed separately.

**Comment by pshipton** [comment]
jenkins test sanity zlinux jdk8

**Comment by pshipton** [comment]
This appears ready to go, assuming the zlinux test passes. It is marked WIP, so I'll wait a while, but I intend to remove the WIP and merge before the nightly tests start at midnight.

**Comment by keithc-ca** [comment]
@pshipton I noticed that this improved the situation, but the OSX sanity test build I started still had a couple failure. Did something else happen to make those failures go away, or was luck involved?

**Comment by pshipton** [comment]
@keithc-ca there aren't any failures in sanity with this fix, there are a still a couple of failures in the extended testing. See https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/278#issuecomment-475909339

**Comment by keithc-ca** [comment]
> Seems to have fixed jdmpview, but the two testDDRExt_* tests must not be using jdmpview and will need to be fixed separately.

https://github.com/eclipse/openj9/pull/5233 should address the remaining failures.

**Pull request merged**
