### PR TITLE
Add a configure option to enable OpenJDK MethodHandles

### PR DESCRIPTION
**Pull request by babsingh**
New configure option: `--enable-openjdk-methodhandles`

This option enables OpenJDK MethodHandles and disables OpenJ9 MethodHandles.

By default, OpenJ9 MethodHandles are enabled.

Related: https://github.com/eclipse/openj9/issues/7352

Co-authored-by: Jack Lu <Jack.S.Lu@ibm.com>
Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>

### CODE REVIEW

**Comment by keithc-ca** [comment]
Please undo the change to autogen.sh, the expected usage is `bash common/autoconf/autogen.sh` which doesn't require the file to have execute permission.

**Comment by babsingh** [comment]
Depends on https://github.com/eclipse/openj9/pull/10540.

**Comment by babsingh** [comment]
> Please undo the change to autogen.sh, the expected usage is `bash common/autoconf/autogen.sh` which doesn't require the file to have execute permission.

It has been removed.

**Comment by keithc-ca** [comment]
Jenkins test sanity plinux,zlinuxcm jdk8

**Review by keithc-ca — APPROVED** [review]

**Pull request merged**
