### PR TITLE
Fix Bug in SunEntries

### PR DESCRIPTION
**Pull request by WilburZjh**
Fixes https://github.com/eclipse-openj9/openj9/issues/15743

Signed-off-by: Jinhang Zhang <Jinhang.Zhang@ibm.com>

### CODE REVIEW

**Comment by WilburZjh** [comment]
Fix the issue mentioned at the [15743](https://github.com/eclipse-openj9/openj9/issues/15743).

**Comment by pshipton** [comment]
jenkins test sanity.openjdk amac jdk8

**Comment by pshipton** [comment]
jenkins compile alinux jdk8

**Comment by pshipton** [comment]
jenkins compile alinux64 jdk8

**Comment by pshipton** [comment]
https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/1250/

**Review by pshipton — APPROVED** [review]

**Pull request merged**
