### PR TITLE
Expand content of debug images

### PR DESCRIPTION
**Pull request by keithc-ca**
Also include OpenJ9 `.map` files on Windows; see eclipse/openj9#10099.

### CODE REVIEW

**Comment by keithc-ca** [comment]
Jenkins test sanity aix,osx,plinux,xlinux,zlinux,win,win32 jdk8

**Comment by keithc-ca** [comment]
Latest push fixes creation of `*.diz` files when configured with `--enable-zip-debug-info`.

**Comment by keithc-ca** [comment]
Jenkins test sanity aix,osx,plinux,xlinux,zlinux,win,win32 jdk8

**Comment by pshipton** [comment]
In the debug image for osx, I don't see any of the OpenJDK .dSYM files.

**Comment by keithc-ca** [comment]
> In the debug image for osx, I don't see any of the OpenJDK .dSYM files.

They were not there before (e.g. see https://ci.eclipse.org/openj9/job/Build_JDK8_x86-64_mac_Personal/504). I'll investigate why.

**Comment by keithc-ca** [comment]
I don't think `.dSYM` folders were ever created for jdk8: `configure` finds `dsymutil` and sets `DSYMUTIL` but nobody uses it.

**Comment by pshipton** [comment]
Created https://github.com/eclipse/openj9/issues/10165 for this problem.

**Pull request merged**
