### PR TITLE
Move CONFIGURE-OPENSSL to CUSTOM-LATE-HOOK to resolve library prefix &

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Moved CONFIGURE-OPENSSL to CUSTOM-LATE-HOOK so as to resolve SHARED-LIBRARY-SUFFIX...

Signed-off-by: andrew-m-leonard <andrew_m_leonard@uk.ibm.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
jenkins compile xLinux

**Comment by pshipton** [comment]
What is the problem this is resolving? i.e. what isn't working that is fixed by this change?

**Comment by mbvreddy** [comment]
This resolves LIBRARY_PREFIX and SHARED_LIBRARY_SUFFIX successfully in #134 so that openssl check with --with-openssl=/path/to/custom/openssl would be successful.

change looks good to me.

**Comment by andrew-m-leonard** [comment]
The provided openssl lib still could not be resolved as the script is looking for:
```
if test -s "$OPENSSL_DIR/lib/${LIBRARY_PREFIX}crypto${SHARED_LIBRARY_SUFFIX}.1.1"; then
```
however SHARED_LIBRARY_SUFFIX is defined later on....!

**Pull request merged**
