### PR TITLE
Remove special cases for AIX

### PR DESCRIPTION
**Pull request by keithc-ca**
`export LDR_CNTRL=MAXDATA=0x40000000` conflicts with the way AIX machines have been set up (and 1GB seems to be insufficient lately).

### CODE REVIEW

**Comment by keithc-ca** [comment]
Other than the copyright addition (which could be removed) this removes any differences from the file from openjdk.

**Comment by pshipton** [comment]
PR testing for this is running in #4286

**Comment by keithc-ca** [comment]
This appears to have fixed eclipse/openj9#4120.

**Comment by pshipton** [comment]
Ignoring the copyright failure since this change reverts the file to remove all IBM changes.

**Comment by pshipton** [comment]
@sxa555 this should fix `virtual memory exhausted` for AIX jdk8, although there will be another failure until https://github.com/eclipse/openj9/pull/4286 is merged as well.

**Pull request merged**
