### PR TITLE
Make openjdk tag search local to branch

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Issue https://github.com/ibmruntimes/openj9-openjdk-jdk/issues/101

Signed-off-by: andrew-m-leonard <andrew_m_leonard@uk.ibm.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
jenkins test sanity xlinux

**Comment by andrew-m-leonard** [comment]
https://hyc-runtimes-jenkins.swg-devops.com/view/OpenJ9%20-%20Personal/job/Pipeline-Build-Test-Personal/2242/

**Comment by pshipton** [comment]
jenkins compile osx,aix,win

**Comment by keithc-ca** [comment]
Now that #296 is merged, there's no need to search for a tag - closing.

**Pull request closed without merging**
