### PR TITLE
Allow building on macOS with XCode 13

### LINKED ISSUE #595: configure: error: Xcode 6, 9-12 is required to build JDK 8, the version found was 13.4.1
I commented out this check and everything seemed to build correctly, so I'll submit a PR with an `|| 13` condition.

### PR DESCRIPTION
**Pull request by kgibm**
Fixes #595

Signed-off-by: Kevin Grigorenko <kevin.grigorenko@us.ibm.com>

### CODE REVIEW

**Comment by kgibm** [comment]
@pshipton Not sure if this is the correct way to fix this or not, and whether all three files should be changed or not as some seem to be auto-generated. The copyright check failed and notes a missing copyright header.

**Comment by pshipton** [comment]
Right, an IBM copyright should be added to toolchain.m4, and the generated files should be re-generated using `bash configure autogen`, which should make the change in the .m4 and update the timestamps.

**Comment by kgibm** [comment]
@pshipton The top of `toolchain.m4` writes:

> \# Copyright (c) 2011, 2018, Oracle and/or its affiliates. All rights reserved.
> \# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.

Should I still add an IBM copyright below that?

Also, running autogen failed:

```
$ bash configure autogen
Running custom generated-configure.sh
configure: WARNING: you should use --build, --host, --target
configure: Configuration created at Wed Jul 27 08:02:48 CDT 2022.
configure: configure script generated at timestamp 1656536820.
[...]
checking build system type... Invalid configuration `autogen': machine `autogen' not recognized
configure: error: /usr/local/bin/bash /Users/kevin/git/openj9-openjdk-jdk8/common/autoconf/build-aux/config.sub autogen failed
```

**Comment by pshipton** [comment]
> Should I still add an IBM copyright below that?

Yes. Example https://github.com/ibmruntimes/openj9-openjdk-jdk8/blob/openj9/common/autoconf/libraries.m4#L27

> running autogen failed

Sorry, I was looking at newer doc. For jdk8 you run `common/autoconf/autogen.sh` and you're supposed to have autoconf 2.69. It might add stuff related to `runstate` to the generated files, but these changes need to be removed.

**Comment by kgibm** [comment]
@pshipton Added the copyright and generated the non-m4 files with autoconf 2.69

**Comment by pshipton** [comment]
jenkins compile xmac jdk8

**Review by pshipton — APPROVED** [review]

**Pull request merged**
