### PR TITLE
Correct --with-openssl lib location

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Signed-off-by: andrew-m-leonard <andrew_m_leonard@uk.ibm.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
jenkins compile xlinux

**Comment by andrew-m-leonard** [comment]
@pshipton Peter please can you review and merge?

**Comment by pshipton** [comment]
I assume this fixes the problem @sxa555 reported via Slack, when setting `--with-openssl=<location>`
```
checking for OPENSSL... no
configure: error: Unable to find openssl in specified location /usr/local/openssl-1.1.1/lib
configure exiting with result code 1
```

**Comment by andrew-m-leonard** [comment]
yes, thanks Peter

**Comment by mbvreddy** [comment]
Also, I believe LIBRARY_PREFIX and SHARED_LIBRARY_SUFFIX variables are not available when checking for openssl. We may need to fix that as well.

**Pull request merged**
