### PR TITLE
Update excluded list for extended.openjdk

### PR DESCRIPTION
**Pull request by WilburZjh**
Signed-off-by: Jinhang Zhang <Jinhang.Zhang@ibm.com>

### CODE REVIEW

**Comment by WilburZjh** [comment]
Updated two failed tests

- [javax/crypto/CipherSpi/TestGCMWithByteBuffer.java](https://github.com/ibmruntimes/openj9-openjdk-jdk8/issues/611#issuecomment-1262741995)
- [sun/rmi/rmic/manifestClassPath/run.sh](https://github.com/ibmruntimes/openj9-openjdk-jdk8/issues/611#issuecomment-1262791680)

**Comment by pshipton** [comment]
@alon-sh for review

**Comment by llxia** [comment]
@alon-sh could you please review the PR when you have time? Thanks

**Comment by alon-sh** [comment]
the first test is fine, the second test that is excluded:

```
sun/rmi/rmic/manifestClassPath/run.sh                               https://github.com/ibmruntimes/openj9-openjdk-jdk8/issues/611   linux-x64
```

@WilburZjh could you give more details on why is this test failing and why should it be excluded rather then fixed?

**Comment by WilburZjh** [comment]
> the first test is fine, the second test that is excluded:
> 
> ```
> sun/rmi/rmic/manifestClassPath/run.sh                               https://github.com/ibmruntimes/openj9-openjdk-jdk8/issues/611   linux-x64
> ```
> 
> @WilburZjh could you give more details on why is this test failing and why should it be excluded rather then fixed?

This jvm option has been removed from other jdk versions. So Im not sure if we need to remove it as well or fix it.

**Comment by alon-sh** [comment]
ok you can keep it excluded. approved.

fyi @llxia @pshipton

**Review by pshipton — APPROVED** [review]

**Pull request merged**
