### PR TITLE
Fix OpenJ9 jvm.dll version for Windows

### PR DESCRIPTION
**Pull request by theresa-m**
Accompanies https://github.com/eclipse/openj9/pull/2189

Signed-off-by: Theresa Mammarella <Theresa.T.Mammarella@ibm.com>

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins compile plinux

**Comment by pshipton** [comment]
I was a little hasty when approving. I don't think this is what we want. It appears JDK_VERSION will be 1.8.0 however I see the dll version is 8.0.0.0 in an AdoptOpenJDK Hotspot Java 8 build, and an Oracle build shows 8.0.1610.12 for build 1.8.0_161-b12

**Comment by theresa-m** [comment]
I'm not able to test this with all the release types. For my build version 1.8.0_162-internal the dll version is 8.0.1620.0

**Comment by pshipton** [comment]
Please add the IBM copyright (using 2018, 2018) to spec.gmk.in.

**Comment by pshipton** [comment]
jenkins compile plinux

**Pull request merged**
