### PR TITLE
Remove blank lines (again)

### PR DESCRIPTION
**Pull request by keithc-ca**
See https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/177.

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
jenkins compile xlinux

**Comment by andrew-m-leonard** [comment]
jenkins test xlinux sanity

**Comment by andrew-m-leonard** [comment]
jenkins test sanity xlinux

**Comment by pshipton** [comment]
I'm going to go ahead and merge this because it blocking all the openj9 tests from passing. 
For the record the as yet uncompleted sanity test is https://ci.eclipse.org/openj9/job/PullRequest-Sanity-JDK8-linux_x86-64_cmprssptrs-OpenJDK8/9/

**Pull request merged**
