### PR TITLE
Merge openj9 to 0.36.0

### PR DESCRIPTION
**Pull request by keithc-ca**
To include https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/642.

### CODE REVIEW

**Review by pshipton — APPROVED** [review]

**Comment by JasonFengJ9** [comment]
@keithc-ca just checking that a PR using `ibmruntimes/openj9` as the source branch is not a bad practice?

**Comment by pshipton** [comment]
> just checking that a PR using ibmruntimes/openj9 as the source branch is not a bad practice?

I don't understand the concern. We do this all the time, i.e. 
https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/640
https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/641

**Comment by JasonFengJ9** [comment]
No functionality concerns, I had an impression that a personal branch is recommended for a PR source, otherwise no objection on the current approach.

**Comment by pshipton** [comment]
No point in creating another branch if the openj9 branch is suitable. Often it is, until there is a change included that we don't want added to the release.

**Comment by JasonFengJ9** [comment]
> No point in creating another branch if the openj9 branch is suitable. Often it is, until there is a change included that we don't want added to the release.

I guess we don't like the feature [Automatic branch deletion](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches)

**Pull request merged**
