### PR TITLE
Update copyright information

### PR DESCRIPTION
**Pull request by ben-walsh**
Signed-off-by: Ben Walsh <ben_walsh@uk.ibm.com>

### CODE REVIEW

**Comment by andrew-m-leonard** [comment]
jenkins compile xlinux

**Comment by ben-walsh** [comment]
jenkins compile xlinux

**Comment by keithc-ca** [comment]
This introduces blank lines in jvm.cfg which will require another change like https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/177.

**Comment by keithc-ca** [comment]
Sanity testing would have caught the problem with blank lines in `jvm.cfg` files.

**Pull request merged**
