### PR TITLE
Enable DDR for more platforms by default

### PR DESCRIPTION
**Pull request by keithc-ca**
Now enabled for p, x and z Linux by default.

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test all

**Comment by keithc-ca** [comment]
We need to get `libdwarf-dev` installed on the build machines before this can be merged: see https://github.com/ibmruntimes/openj9-openjdk-jdk9/pull/143#issuecomment-375137029

**Comment by pshipton** [comment]
Created https://github.com/eclipse/openj9/issues/1506

**Comment by jdekonin** [comment]
Machines have packages installed.  Seems I don't have the ability to kick off a build though.

**Comment by jdekonin** [comment]
jenkins compile zlinux plinux

**Comment by pshipton** [comment]
jenkins test all zlinux plinux

**Comment by pshipton** [comment]
jenkins test all zlinux,plinux

**Pull request merged**
