### PR TITLE
Enable cmake by default for Windows 32-bit builds

### PR DESCRIPTION
**Pull request by keithc-ca**
Enabled by eclipse/openj9#11986.

### CODE REVIEW

**Comment by keithc-ca** [comment]
I forgot to run `autogen.sh`.
I have rebased this on the `openj9-staging` branch, but I'll let that content promote to the `openj9` before marking this ready for review.

**Comment by pshipton** [comment]
I've promoted openj9-staging to openj9 now. Note this is a dup of #483

**Comment by keithc-ca** [comment]
> I've promoted openj9-staging to openj9 now. Note this is a dup of #483

Except that #483 has a merge conflict.

**Comment by pshipton** [comment]
jenkins test sanity win32cm jdk8

**Comment by pshipton** [comment]
jenkins test sanity win32 jdk8

**Comment by keithc-ca** [comment]
@dnakamura Can you please look at the build errors, please.

I tried a build myself, but it failed much earlier with an error for `libffi/x86/win32.S` (which, I assume, indicates a problem with my system).

**Comment by keithc-ca** [comment]
On that same system, a 32-bit UMA build succeeds.

**Comment by dnakamura** [comment]
Currently trying to replicate locally, but I believe its a matter of a missing flag to masm which must have gotten dropped in rebasing.  Not sure about @keithc-ca s libffi error (unless its also unresolved symbols)

**Comment by keithc-ca** [comment]
Here are the diagnostics for the ffi failure:
```
[ 58%] Generating win32.asm
win32.S
[ 58%] Building ASM_MASM object runtime/libffi/CMakeFiles/ffi.dir/win32.asm.obj
 Assembling: C:\space\jdk08\build\win32\vm\runtime\libffi\win32.asm
C:\space\jdk08\build\win32\vm\runtime\libffi\win32.asm(1206)e too large for specified size
C:\space\jdk08\build\win32\vm\runtime\libffi\win32.asm(1206) : warninC:\space\jdk08\build\win32\vm\runtime\libffi\win32.asm(1378)e too large for specified size
C:\space\jdk08\build\win32\vm\runtime\libffi\win32.asm(1378) : warninC:\space\jdk08\build\win32\vm\runtime\libffi\win32.asm(1191)r local not referenced : FORCEFRAME
C:\space\jdk08\build\win32\vm\runtime\libffi\win32.asm(1206)r local not referenced : FORCEFRAME
C:\space\jdk08\build\win32\vm\runtime\libffi\win32.asm(1289)r local not referenced : FORCEFRAME
```

**Comment by dnakamura** [comment]
Issue was a result of `enable_language` clobbering our asm flags. However flags would then get re-applied properly on a partial rebuild. Should be fixed by eclipse/openj9#12091. 

Was not able to replicate the ffi issue, but its possible that the pr also solves that as well.

**Comment by keithc-ca** [comment]
Jenkins test sanity win32 jdk8

**Review by pshipton — APPROVED** [review]

**Pull request merged**
