### PR TITLE
CMake: add SHA and jdk version numbers

### PR DESCRIPTION
**Pull request by dnakamura**
Mirrors changes in later JDKs

Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>

### CODE REVIEW

**Comment by dnakamura** [comment]
Should fix eclipse/openj9#11855

**Comment by pshipton** [comment]
jenkins compile zlinux jdk8

**Comment by pshipton** [comment]
jenkins compile plinux jdk8

**Comment by pshipton** [comment]
Testing via grinder https://ci.eclipse.org/openj9/view/Test/job/Grinder/1492/ - passed

**Review by pshipton — APPROVED** [review]

**Pull request merged**
