### PR TITLE
Add J9JCL to sourcepath for generating beaninfo

### PR DESCRIPTION
**Pull request by keithc-ca**
Fixes (apparently benign) errors noted in https://github.com/eclipse-openj9/openj9/issues/18500.

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins compile alinux64 jdk8

**Comment by pshipton** [comment]
Do the later versions need a similar change?

**Comment by keithc-ca** [comment]
I don't think so. The makefile structure in Java 8 is very different.

**Review by pshipton — APPROVED** [review]

**Comment by pshipton** [comment]
Pls cherry pick for 0.43

**Comment by pshipton** [comment]
Actually never mind, I can push it.

**Comment by pshipton** [comment]
https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/709

**Pull request merged**
