### PR TITLE
Use configured git command

### PR DESCRIPTION
**Pull request by keithc-ca**
Use `$(GIT)` instead of `git` in makefiles.

### CODE REVIEW

**Comment by keithc-ca** [comment]
Change was motivated by [8210283: Support git as an SCM alternative in the build](https://github.com/ibmruntimes/openj9-openjdk-jdk8/commit/ae7431401c598f4a9f31bdb13b2887c5e39b213e); `GIT` was already defined in newer openjdk versions.

**Comment by pshipton** [comment]
jenkins line endings check

**Comment by pshipton** [comment]
jenkins signed off by check

**Comment by pshipton** [comment]
jenkins compile plinux jdk8

**Pull request merged**
