### PR TITLE
Parse jar index when using SCC

### PR DESCRIPTION
**Pull request by hangshao0**
If a jarIndex exists, the JDK by default (i.e. SCC is off) uses the URLs in the JarIndex to search for resources, the class path in manifest is ignored.

However, when SCC is on, the jarIndex is always ignored and the class path in manifest is used, which differs from the default JDK behavior.

Change SCC code in URLClassPath to always use URLs in jarIndex if it exists.

Add a property "com.ibm.oti.shared.disableJarIndex" that can be used to control the behavior.

JarIndex is removed in Java 21, no need to port to Java 21+.

port of https://github.com/ibmruntimes/openj9-openjdk-jdk17/pull/331

Internal issue semeru-runtimes/issues/1

### CODE REVIEW

**Comment by pshipton** [comment]
jenkins test sanity,extended alinux jdk8

**Comment by pshipton** [comment]
```
17:18:17  /home/jenkins/workspace/Build_JDK8_aarch64_linux_Personal/jdk/src/share/classes/sun/misc/URLClassPath.java:109: error: cannot find symbol
17:18:17          DISABLE_JAR_INDEX = p != null ? p.equals("true") || p.isEmpty() : false;    //OpenJ9-shared_classes_misc
17:18:17          ^
17:18:17    symbol:   variable DISABLE_JAR_INDEX
17:18:17    location: class URLClassPath
17:18:17  /home/jenkins/workspace/Build_JDK8_aarch64_linux_Personal/jdk/src/share/classes/sun/misc/URLClassPath.java:1330: error: cannot find symbol
17:18:17              if (usingSharedClasses && !DISABLE_JAR_INDEX) {                                               //OpenJ9-shared_classes_misc
17:18:17                                         ^
17:18:17    symbol:   variable DISABLE_JAR_INDEX
17:18:17    location: class JarLoader
```

**Comment by hangshao0** [comment]
jenkins test sanity,extended alinux jdk8

**Comment by hangshao0** [comment]
PR builds passed.

**Review by pshipton — APPROVED** [review]

**Pull request merged**
