### PR TITLE
Make bash version check more inclusive

### PR DESCRIPTION
**Pull request by DanHeidinga**
close: #290

Signed-off-by: Dan Heidinga <daniel_heidinga@ca.ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
Jenkins compile plinux,zlinux,osx jdk8

**Comment by DanHeidinga** [comment]
Jenkins compile win jdk8

**Comment by DanHeidinga** [comment]
Note, this fix is already used in the  jdk11 & 12 repos.  I haven't confirmed the jdk repo but would be surprised if it wasn't already the case

**Comment by keithc-ca** [comment]
> I haven't confirmed the jdk repo but would be surprised if it wasn't already the case

The version check is now consistent across all repos.

**Pull request merged**
