### PR TITLE
Handle race condition in shared classes defineClass()

### PR DESCRIPTION
**Pull request by pdbain-ibm**
Handle IllegalArgumentException when parallel classloaders define the same
package.  cf. https://github.com/eclipse/openj9/issues/3038

Also cleaned up the indentation, so review with whitespace changes suppressed (`?w=1` in URL).

FYI @pshipton.

Signed-off-by: Peter Bain <peter_bain@ca.ibm.com>

### CODE REVIEW

**Comment by pdbain-ibm** [comment]
Running a personal build now.

**Comment by pdbain-ibm** [comment]
Personal build passed 3/4 platforms.  One test in progress.  Please review.  Do I need to make the same change in the other repos?

**Comment by pshipton** [comment]
>  Do I need to make the same change in the other repos?

Possibly. Please check the code, it is different because of modularity.

**Comment by pshipton** [comment]
jenkins test sanity zlinux

**Comment by pshipton** [comment]
jenkins test sanity xlinux

**Comment by pshipton** [comment]
jenkins test sanity zlinux

**Pull request merged**
