### PR TITLE
update exclude list for fips

### PR DESCRIPTION
**Pull request by WilburZjh**
Closes https://github.com/eclipse-openj9/openj9/issues/16412

### CODE REVIEW

**Comment by pshipton** [comment]
@WilburZjh your commit is not signed and is failing the check. Pls update the commit with a Signed-off-by.

**Comment by WilburZjh** [comment]
updated

**Comment by pshipton** [comment]
It doesn't look like there is a blank line between the title and the Signed-off-by line. There should be a blank line before the Signed-off-by.

**Comment by pshipton** [comment]
Ok, I see there is a blank line, it's just not obvious when looking via github.

**Pull request merged**
