### PR TITLE
Script for Create automated process in the open to refresh extensions repo with openjdk changes

### PR DESCRIPTION
**Pull request by archanaNogriya**
Script for Create automated process in the open to refresh extensions
repo with openjdk changes

Signed-off-by: Archana Nogriya  archana.nogriya@uk.ibm.com

### CODE REVIEW

**Comment by archanaNogriya** [comment]
@AdamBrousseau  let me know if you can see now please ?

**Comment by archanaNogriya** [comment]
2nd one is with right email id.

**Comment by jdekonin** [comment]
This is sort of irrelevant since that last pull request was merged already (which you shouldn't be merging your own content).  I don't see why we would push 2 more commits with no value-add.

**Comment by AdamBrousseau** [comment]
I agree. Although the last PR was lacking the proper commit signature and Issue reference, I don't think it is worth redoing. Closing this PR.

**Comment by archanaNogriya** [comment]
Agreed thanks @AdamBrousseau

**Pull request closed without merging**
