### PR TITLE
OpenSSL crypto support for OpenJ9-OpenJDK build

### PR DESCRIPTION
**Pull request by mbvreddy**
Issue #115

Add support to use OpenSSL native implementation for some Cryptography Algorithms in OpenJ9 build. By default, this support is disabled (as of now). Below system properties are in place to control it

-Djdk.nativeCrypto=true
-Djdk.nativeDigest=true
-Djdk.nativeCBC=true
-Djdk.nativeGCM=true

New JNI library **jnicrypto** is created as part of this and is bundled with final JDK. However, there is no plan to ship OpenSSL libraries with OpenJ9. 

This is enabled on all platforms except for zOS and Windows.

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
Please note that the [Eclipse OpenJ9 Jenkins](https://ci.eclipse.org/openj9/) builds do not use Adopt build scripts. Is this something we need to support in Pull Request builds and Nightly builds?

**Comment by mbvreddy** [comment]
I am working on to make it independent of AdoptOpenJDK scripts. As of now this PR is for reference and is WIP.

**Comment by vsebe** [comment]
@mbvreddy - according to https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/493, you do not need to download openssl 1.1.0. It should be installed on all of the xlinux machines via ansible.

**Comment by mbvreddy** [comment]
@vsebe may I know if openssl v1.1.0 installed on build machines are recognizable by pkg-config? The command `pkg-config --modversion openssl` would give correct version?

**Comment by vsebe** [comment]
@mbvreddy - no, it is not recognizable by pkg-config. openssl 1.1.0 is installed from source, its installation directory is /usr/local. In order to be recognizable by pkg-config, PKG_CONFIG_PATH has to be set up:
```
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib64/pkgconfig/
pkg-config --modversion openssl
1.1.0g
```

**Comment by pshipton** [comment]
After this is merged, it seems we should just modify the builds to use `--openssl-version=1.1.0` or `--openssl-version=1.1.1` and not require that openssl be pre-installed on the build machines. Its only pre-installed on Linux, for another purpose, and I'm not sure if the header files are there. I suspect they are not.

**Comment by pshipton** [comment]
Note the copyright check is failing, and some of the files need to have an IBM copyright line added.

09:34:44 jdk/make/lib/SecurityLibraries.gmk
09:34:44 jdk/src/share/classes/com/sun/crypto/provider/CipherCore.java
09:34:44 jdk/src/share/classes/sun/security/provider/SunEntries.java

Also the Signed-off-by check is failing because one of the commits is missing a Signed-off-by

**Comment by pshipton** [comment]
@mbvreddy other than fixing the copyright problems, is there anything else blocking removing the WIP from this PR, is it ready to be reviewed?

**Comment by mbvreddy** [comment]
@pshipton this PR is now ready for review. Few things

copyright check is failing for .gitignore and common/autoconf/generated-configure.sh. 
   .gitignore file did not had copyright before my change. Do I need to add it?
   common/autoconf/generated-configure.sh is generated automatically from autoconf files. Should we need to change the copyright year manually?

I'll squash the multiple commits to single shortly.

**Comment by pshipton** [comment]
Thanks @mbvreddy, the remaining copyright failures can be ignored.

The remaining issue I'm aware of, I expect the builds to continue working if no openssl options are specified. It is fine to modify the java code and check for the existence of libraries. However if no openssl options are specified to the build, the build should still succeed without creating or using an openssl library.

This change should be deliverable without requiring all users to modify their builds.

**Comment by pshipton** [comment]
Created an issue at Adopt https://github.com/AdoptOpenJDK/openjdk-build/issues/604

**Comment by pshipton** [comment]
Also an issue at OpenJ9 https://github.com/eclipse/openj9/issues/3118

**Comment by mbvreddy** [comment]
Have pushed couple of code changes to download and build OpenSSL 1.1.1

@pshipton I've started working on code changes to allow building OpenJ9-openjdk build if no OpenSSL configure options are specified.

**Comment by mbvreddy** [comment]
This PR introduce following classes to enable OpenSSL crypto support (with configure option `--with-openssl`).

**in jre/lib/rt.jar**

> jdk/crypto/jniprovider/NativeCrypto.class
> sun/security/provider/NativeDigest.class
> sun/security/provider/NativeSHA2.class
> sun/security/provider/NativeSHA2$SHA224.class
> sun/security/provider/NativeSHA2$SHA256.class
> sun/security/provider/NativeSHA5.class
> sun/security/provider/NativeSHA5$SHA384.class
> sun/security/provider/NativeSHA5$SHA512.class

**in jre/lib/ext/sunjce_provider.jar**

> com/sun/crypto/provider/NativeCipherBlockChaining.class
> com/sun/crypto/provider/NativeGaloisCounterMode.class

**in jre/lib/[arch]/**

> libjncrypto.dll (which has native implementation for methods in  jdk/crypto/jniprovider/NativeCrypto.class)


When `--with-openssl` configure option is not provided, only jdk/crypto/jniprovider/NativeCrypto.class is shipped in rt.jar. All other classes and jni library won't get bundled in final JDK build.

When `--with-openssl` configure option is provided along with `--enable-openssl-bundling` will additionally copy libcrypto.so.1.1 (on Unix platform), libcrypto-1_1-x64.dll (on Windows 64-bit), libcrypto-1_1.dll (on Windows 32-bit)

**Comment by andrew-m-leonard** [comment]
Review comments:
1. jdk/make/lib/SecurityLibraries.gmk has incorrectly changed the Oracle Copyright date
2. jdk/src/share/classes/sun/security/provider/SunEntries.java has incorrectly changed the Oracle Copyright date
3. jdk/make/CreateSecurityJars.gmk missing IBM Copyright
4. Several of the new closed/adds/..source files are obviously based from Oracle OpenJDK source, and thus need the Oracle GPL copyright, at least the following I suspect? :
```
closed/adds/jdk/src/share/classes/com/sun/crypto/provider/NativeCipherBlockChaining.java
closed/adds/jdk/src/share/classes/com/sun/crypto/provider/NativeGaloisCounterMode.java
closed/adds/jdk/src/share/classes/sun/security/provider/NativeDigest.java
```

**Comment by andrew-m-leonard** [comment]
Talking to Bhakta at the moment, running jtreg tests:   make jdk_security for jdk8 built with no openssl fails java.lang.NoClassDefFoundError....
Bhakta investigating

**Comment by andrew-m-leonard** [comment]
TEST STATS: name=jdk_security  run=995  pass=691  fail=304
EXIT CODE: 3
EXIT CODE: 3

**Comment by mbvreddy** [comment]
Only way to resolve java.lang.NoClassDefFoundError is to ship all dependent classes (those we introduced to enable OpenSSL crypto) in JDK even if --with-openssl is not specified. I am reverting the changes I made earlier not to ship those.

**Comment by mbvreddy** [comment]
@andrew-m-leonard I have fixed copyright issue except to review comment 4. Those classes in closed/adds folder are new files created by IBM (though it has same method names as that of their Oracle counter parts i.e.,CipherBlockChaining.java & GaloisCounterMode.java). Do you think it should still carry Oracle copyright as well? If yes, what should we mention year as (2018, 2018)? or same year as its Oracle counter part.

**Comment by mbvreddy** [comment]
Had a chat with Andrew and understand that Oracle copyright should be there for those 3 new files. So, have added it and pushed.

**Comment by andrew-m-leonard** [comment]
thanks @mbvreddy i've re-run jdk_security tests on a "without openssl" build, and success now :-)

**Comment by andrew-m-leonard** [comment]
jenkins compile xlinux

**Comment by andrew-m-leonard** [comment]
CI Build actually passed!

**Pull request merged**
