### PR TITLE
WIP: Apply JVM_ZipHook patch

### PR DESCRIPTION
**Pull request by groeges**
Signed-off-by: Steve Groeger <GROEGES@uk.ibm.com>

### CODE REVIEW

**Comment by groeges** [comment]
jenkins test sanity.functional win,win32 jdk8

**Comment by groeges** [comment]
jenkins test sanity.functional win,win32

**Comment by groeges** [comment]
jenkins build win,win32

**Comment by groeges** [comment]
Jenkins test sanity win,win32 jdk8

**Comment by groeges** [comment]
PR test / compile jobs are currently broken. Will run a test job when fixed.

**Comment by AdamBrousseau** [comment]
Jenkins test sanity win,win32 jdk8

**Comment by groeges** [comment]
@pshipton Please can someone decide on whether this should be delivered or not. In the issue, https://github.ibm.com/runtimes/openjdk-contribution/issues/10, Dan is saying we should deliver this for Java 8. but you seem to be saying not.  
Please can someone decide one way or the other to save us wasting our time on this.

**Comment by groeges** [comment]
@pshipton Just so you know, this PR implements the same change that is in the IBM Java 8, so if this code has drawbacks then these probably exist in that release as well.

**Comment by pshipton** [comment]
> this PR implements the same change that is in the IBM Java 8, so if this code has drawbacks then these probably exist in that release as well.

Understood. This doesn't mean we need to release the same change for OpenJ9 builds, if we have a strategy to do something better.

**Comment by groeges** [comment]
Agree

**Comment by pshipton** [comment]
This is replaced by https://github.com/eclipse/openj9/pull/6174

**Pull request closed without merging**
