### PR TITLE
Include j9aixbaddep in test-image artifacts

### PR DESCRIPTION
**Pull request by keithc-ca**
Fixes: eclipse/openj9#3942

### CODE REVIEW

**Comment by DanHeidinga** [comment]
Jenkins test sanity aix jdk11

**Comment by DanHeidinga** [comment]
Jenkins test sanity aix jdk8

**Comment by DanHeidinga** [comment]
@keithc-ca are there PRs for JDK11, jdk extension repos as well?

**Comment by keithc-ca** [comment]
> @keithc-ca are there PRs for JDK11, jdk extension repos as well?

Yes: https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/74 and https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/58.

**Pull request merged**
